name: microservice-spring-demo

services:

  postgres-spring:
    container_name: spring-postgres
    image: postgres:14
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5432:5432"
    networks:
      - spring-net
    volumes:
      - ./postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.24
    ports:
      - "9411:9411"
    networks:
      - spring-net

  spring-order:
    container_name: spring-order
    build:
      context: ./microservice-spring-order
    image: spring-microservices/order:latest
    ports:
      - "18081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-spring:5432/dborder
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: dbpass
    depends_on:
      - postgres-spring
      - zipkin
    networks:
      - spring-net

  spring-shipping:
    container_name: spring-shipping
    build:
      context: ./microservice-spring-shipping
    image: spring-microservices/shipping:latest
    ports:
      - "18083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-spring:5432/dbshipping
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: dbpass
    depends_on:
      - postgres-spring
      - spring-order
      - zipkin
    networks:
      - spring-net

  spring-invoicing:
    container_name: spring-invoicing
    build:
      context: ./microservice-spring-invoicing
    image: spring-microservices/invoicing:latest
    ports:
      - "18082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-spring:5432/dbinvoicing
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: dbpass
    depends_on:
      - postgres-spring
      - spring-order
      - zipkin
    networks:
      - spring-net

  prometheus:
    container_name: spring-prometheus
    build:
      context: ./prometheus
    image: spring-microservices/prometheus:latest
    ports:
      - "9090:9090"
    depends_on:
      - spring-order
      - spring-shipping
      - spring-invoicing
    networks:
      - spring-net

  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge